run_id: "neon_empty_db"
backend: NEON

operations: READ
operations: INSERT
operations: UPDATE
operations: RANGE_UPDATE
operations: BRANCH

num_ops: 500

table_name: "customer"

starting_branch: ""

database_setup {
  db_name: "microbench"
  cleanup: true

  sql_dump {
    sql_dump_path: "db_setup/tpcc_schema.sql"
  }
}

range_update_config {
  range_size: 100
}

autocommit: true
